version: '3.8'

services:
  mariadb:
    build: ./mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  wordpress:
    build: ./wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - backend

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html:ro
    depends_on:
      - wordpress
    networks:
      - backend

volumes:
  mariadb_data:
  wordpress_data:

networks:
  backend:
