---
- name: Install MariaDB
  apt:
    name: mariadb-server
    state: present
    update_cache: yes

- name: Ensure MariaDB is running and enabled
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Secure MariaDB (remove anonymous user, test DB)
  mysql_secure_installation:
    login_user: root
    login_password: ''
    new_password: "{{ mariadb_root_password }}"
    login_host: "localhost"
    user: root
    config_file: /etc/mysql/debian.cnf
    remove_test_db: true
    remove_anonymous_user: true
    disallow_remote_root: true
  ignore_errors: true

- name: Create database
  mysql_db:
    name: "{{ mariadb_database }}"
    state: present

- name: Create user
  mysql_user:
    name: "{{ mariadb_user }}"
    password: "{{ mariadb_password }}"
    priv: "{{ mariadb_database }}.*:ALL"
    host: "localhost"
    state: present
