---
- name: Installer les dépendances
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
    update_cache: yes
    state: present

- name: Ajouter la clé GPG de Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Ajouter le dépôt Docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Installer Docker et Docker Compose
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']
    update_cache: yes
    state: latest

- name: S'assurer que Docker est lancé
  service:
    name: docker
    state: started
    enabled: yes
